### ISSUE TITLE
Mailer: dots in email addresses cause delivery failures

### ISSUE THREAD

**Issue by vLooz** [lavab/mailer#55] opened 2015-06-06 12:23 UTC
what happened:
Someone wanted to send an email from his gmail-address to felix.vlooz@lavaboom.com and to felix@lavaboom.com
My username is actually shown as felix.vlooz in Settings/Profile, so I didn't expect this to be a problem anymore. He got a delivery failure notice, stating that the mail to felix.vlooz@lavaboom.com could not be delivered. There was no info about the delivery to felix@lavaboom.com, so we expected at least this mail to be gone though. But it didn't reach Felix.

what should have happened:
The dot problem should not be a problem anymore, neither during SignUp/LogIn nor when sending a mail from a non-lavaboom account to Lavaboom. People are used to have dots in their addresses to separate them optically and it's not really good UX to force them to think otherwise.

**Comment by joergG** [comment] 2015-07-16 09:54
@vLooz and me can't reproduce this problem anymore, therefore closing it.

**Closed** 2015-07-21 12:41 UTC
Labels: bug, important, in progress

**Comment by joergG** [comment] 2015-07-21 14:43
@andreis - dunno why I added "in progress"-label.
just wanted to close this since fvl and me weren't able to reproduce the behaviour anymore.
not sharing this impression?  :-)

**Comment by andreis** [comment] 2015-07-21 19:19
No, I just meant that I have no idea what happened there - I surely haven't removed that label. Did we find a Github bug? :smile:
